### ISSUE TITLE
Collaboration Request!

### ISSUE THREAD

**Issue by MarketingPip** [ccrma/webchuck-ide#11]
Hey guys!

I am building a project that I think will be more than useful to you guys! As well be useful to me / the project in general to have you guys commit back. 

I will keep you posted in a few days with repo and hopefully we can go from there. 

Maybe too if it is useful to you guy's  - you can possibly try and convince Stanford to sponsor the repo. 

Keep you posted! 👍

**Comment by terryzfeng** [comment]
Apologies for not seeing this earlier, I'd love to follow up on this

**Comment by terryzfeng** [comment]
If you have any updates, feel free to share, otherwise I'll close this issue for now! @MarketingPip

**Comment by MarketingPip** [comment]
@terryzfeng - hey I did not mean to leave this hanging, more than interested in getting collaboration on this. I will create a repo and invite you to look over it, hopefully you don't puke looking at the code! lol (not separated into nice imported libraries and just a gross single HTML file). 

I will invite you shortly and then we can discuss from there! 👍

**Comment by terryzfeng** [comment]
Awesome looking forward to it!

**Comment by terryzfeng** [comment]
Feel free to reopen the issue when ready!
