### ISSUE TITLE
Monaco Editor variable auto suggestion and improved hover documentation

### ISSUE THREAD

**Issue by terryzfeng** [ccrma/webchuck-ide#19]
@42x00 
Would be a good idea for the Chuck-a-thon :)

**Comment by 42x00** [comment]
Yea, it requires chuck code parsing in monaco, tried in last hackathon, was too hard to finish 😂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: terry feng ***@***.***>
Sent: Monday, April 8, 2024 4:01:25 PM
To: ccrma/webchuck-ide ***@***.***>
Cc: Yikai Li ***@***.***>; Mention ***@***.***>
Subject: [ccrma/webchuck-ide] Monaco auto suggestion of previously typed variable names (Issue #19)


@42x00<https://github.com/42x00>
Would be a good idea for the Chuck-a-thon :)

**Comment by terryzfeng** [comment]
Awesome, we could tackle it this time around then. And perhaps fix the formatting of the hover suggestions haha

**Comment by terryzfeng** [comment]
Implemented variable auto suggestion in https://github.com/ccrma/webchuck-ide/commit/32fd3cd360186907568a9805a2d3872a529cda16

Just need to look into documentation hover improvements.
