### ISSUE TITLE
npm install (fedora 40) -- hangs at inflight install

### ISSUE THREAD

**Issue by cchafe** [ccrma/webchuck-ide#33]
Trying to get node going as indicated...
~/webchuck-ide$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
npm WARN deprecated xterm-addon-fit@0.8.0: This package is now deprecated. Move to @xterm/addon-fit instead.
npm WARN deprecated xterm@5.3.0: This package is now deprecated. Move to @xterm/xterm instead.
npm WARN deprecated xterm@4.19.0: This package is now deprecated. Move to @xterm/xterm instead.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
**npm WARN deprecated inflight@1.0.6:** This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

**Comment by terryzfeng** [comment]
Hi Chris, what version of npm and node are you running? 

```
npm --version
```
```
node --verion
```

I can try to reproduce this on the CCRMA linux machines, perhaps bumping the xterm package version.

**Comment by cchafe** [comment]
Thanks, this is using the package for fedora 40, CCRMA may be lagging a bit

cc@fedora:~$ npm --version
6.14.15
cc@fedora:~$ node --version
v14.18.2

**Comment by terryzfeng** [comment]
I think you might need to update your node version (which will bump npm). 

I was able to run `npm install` successfully on the CCRMA Linux Machine.

```
$ node --version
v18.19.0
$ npm --version
10.2.3
```

**Comment by cchafe** [comment]
fedora 40 workstation needs **nvm** to navigate versions and -- issue resolved after using the following hints
https://developer.fedoraproject.org/tech/languages/nodejs/nodejs.html
https://github.com/nvm-sh/nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
then
**nvm install 18**
and
npm install
npm run dev
works!
