### ISSUE TITLE
project export zip file name

### ISSUE THREAD

**Issue by cchafe** [ccrma/webchuck-ide#35]
Not an issue... but a suggestion.
The default name is project.zip
Could the export dialog either provide a field for the project name, or just default to the title?

**Comment by terryzfeng** [comment]
If you set the browser (I'm assuming firefox) to ask where to save files, it'll give you a chance to rename the .zip file before it downloads. Of course, when it unzips, the folder name might still be `project`

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5fab6ee8-3d17-4b7f-8d8a-e1709ad76e71">

**Comment by cchafe** [comment]
Right, there's always that -- how to streamline the user experience is the goal

**Comment by terryzfeng** [comment]
Added descriptive titles, currently on `dev` branch
