### ISSUE TITLE
project export limited to .ck plus one file

### ISSUE THREAD

**Issue by cchafe** [ccrma/webchuck-ide#36]
Looks like export of a project with a .ck that references two files (for example, two time series data files), only exports one of those to the exported project.

**Comment by terryzfeng** [comment]
Just to confirm, this is only happening to you for "Export to WebChucK" right? I was able to reproduce it for that case but not normal ChucK export. It seems like something fishy is going on with the filesystem...will investigate.

**Comment by terryzfeng** [comment]
I looked at this further and it is just that all files except for the active file in the editor are exported as auxiliary files. So you just need to make sure that you are looking at the .ck file for the other two files to be exported. I can try to improve this in the export page.

**Comment by terryzfeng** [comment]
I added a manual selection for the WebChucK main ChucK file to mitigate this confusion! The main .ck file gets embedded into the `index.html`. All other files (.csv etc.) are attached as other auxiliary files. 

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/4e235536-87b1-4691-9c8f-abef7379044d">

```
dir
\
 - index.html
 - phase1.csv
 - phase2.csv
```
