### ISSUE TITLE
ChuGL Support in Web IDE (Maybe with WebGL 2)

### ISSUE THREAD

**Issue by anonimo82** [ccrma/webchuck-ide#41]
Hello everyone.
As in subject, is ChuGL support planned for WebChuck?
If not, will you consider the idea?

Thanks for anything.

Regards, have a nice day.

**Comment by gewang** [comment]
(copying our conversation from the ChucK Discord server) We have been working on this; in fact we have completely moved the ChuGL backend to WebGPU partly for this reason. Despite WebGPU's premise (and promises), the integration has proven very tricky in practice as WebGPU's own API and implementation continue to evolve, with multiple platforms, vendors, etc. But yes getting ChuGL working on the web is a big overarching goal of ours

**Comment by anonimo82** [comment]
Yes, thanks. I guess this should be closed now
