### ISSUE TITLE
Shred created by Machine.add() is lost

### ISSUE THREAD

**Issue by lmaxwell** [ccrma/webchuck-ide#9]
To reproduce: upload a hello.ck file,  execute "Machine.add("hello,ck")" from editor.

The shred related to hello.ck is not visible in the visualizer and also cannot be removed by the "Remove" button on the top.

**Comment by terryzfeng** [comment]
Hi @lmaxwell, with WebChucK IDE, the shred table will only show threads that are running and started by you. `Machine.add` shreds, `Machine.eval()` or even sporked shreds won't show up. To remove shreds from the Machine, you can do `Machine.removeLastShred()`, `Machine.removeAllShreds()`, or even `Machine.clearVM()`.
